name: sitama
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependensi yang dibutuhkan oleh project
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  table_calendar: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # Aset untuk gambar
  assets:
    - assets/logo.jpeg
    - assets/PoliteknikNegeriSemarang.png
    - assets/google.png
    - assets/kalender.png # <-- DITAMBAHKAN untuk ikon kalender kosong